INSERT INTO roles (name, created_at, created_by)
VALUES
    ('ROLE_ADMIN', CURRENT_TIMESTAMP, 'FLYWAY'),
    ('ROLE_EMPLOYER', CURRENT_TIMESTAMP, 'FLYWAY'),
    ('ROLE_JOB_SEEKER', CURRENT_TIMESTAMP, 'FLYWAY');