apiVersion: v1
kind: ConfigMap
metadata:
  name: jobportal-config
  namespace: jobportal
data:
  DB_URL: jdbc:mysql://jobportal-mysql:3306/jobportaldb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  DB_USERNAME: jobportal

  MYSQL_DATABASE: jobportaldb
  MYSQL_USER: jobportal

  APP_CORS_ALLOWED_ORIGINS: http://localhost:30080,http://localhost:8080
  LOG_LEVEL: INFO
