apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal-mysql
  namespace: jobportal
  labels:
    app: jobportal-mysql
spec:
  replicas: 1

  selector:
    matchLabels:
      app: jobportal-mysql

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: jobportal-mysql

    spec:
      containers:
        - name: mysql
          image: jobportal-mysql:8.4
          imagePullPolicy: Never

          ports:
            - name: mysql
              containerPort: 3306

          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: jobportal-config
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: jobportal-config
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jobportal-secret
                  key: DB_PASSWORD

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jobportal-secret
                  key: MYSQL_ROOT_PASSWORD

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            periodSeconds: 10
            failureThreshold: 60

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: jobportal-mysql-pvc