services:
  # CSDL MySQL
  mysql-db:
    image: mysql:8.0
    container_name: job_portal_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: job_portal
      MYSQL_USER: hunghayho
      MYSQL_PASSWORD: hunghayho
    ports:
      - "3308:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BE/src/main/resources/sql/jobportal-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./BE/src/main/resources/sql/jobportal-data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      - backend-networks
    # Cấu hình kiểm tra sức khỏe của database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s        # Cứ mỗi 5 giây kiểm tra lại một lần
      timeout: 5s         # Quá 5 giây không phản hồi coi như thất bại một lần
      retries: 10         # Thử lại tối đa 10 lần
      start_period: 15s   # Thời gian chờ ban đầu để MySQL khởi tạo cơ sở dữ liệu (không tính vào số lần thất bại)

  redis-cache:
    image: redis:alpine
    container_name: job_portal_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - backend-networks
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Spring Boot Backend
  backend:
    build: 
      context: ./BE
      dockerfile: Dockerfile
    container_name: job_portal_be
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/job_portal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=hunghayho
      - SPRING_DATASOURCE_PASSWORD=hunghayho
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      mysql-db:
        condition: service_healthy # Chỉ khởi động khi mysql-db đã vượt qua bài kiểm tra healthcheck bên trên
      redis-cache:
        condition: service_healthy
    networks:
      - frontend-networks # Nối với frontend
      - backend-networks  # Nối với database


  # React Frontend
  frontend:
    build: 
      context: ./FE
      dockerfile: Dockerfile
    container_name: job_portal_fe
    ports:
      - "5173:80" 
    depends_on:
      backend:
        condition: service_started
    networks:
      -  frontend-networks

volumes:
  mysql_data:

networks:
  frontend-networks:
    driver: bridge
  backend-networks:
    driver: bridge